name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Docker Build Tag
        run: echo temporaliotest/replay-versioning-demo:${{ github.run_id }}-${{ github.run_number }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: temporaliotest/replay-versioning-demo:${{ github.run_id }}-${{ github.run_number }}
          platforms: linux/amd64,linux/arm64
          build-args: |
            BUILD_ID=${{ github.run_id }}-${{ github.run_number }}
